
export const enum Service {
  TECHNICAL_ASSISTANCE = 'TECHNICAL_ASSISTANCE',
  RENOVATIONS_REPAIRS = 'RENOVATIONS_REPAIRS',
  LESSON = 'LESSON',
  AUTOMOBILES = 'AUTOMOBILES'
};

export enum SocialNetworkEnum {
  FACEBOOK = "FACEBOOK",
  INSTAGRAM = "INSTAGRAM",
  TWITTER = "TWITTER",
  LINKEDIN = "LINKEDIN",
  YOUTUBE = "YOUTUBE",
};